name: 'A prebuild Alpine Vlang testing container'
description: 'This Alpine container allows for building and testing V in a Docker environment'
author: 'Delyan Angelov <delyan@bulsynt.org>'
inputs: 
  params:
    description: 'The parameters of the entrypoint executable'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.params }}
